steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['install -g pnpm']
  - name: 'ubuntu'
    entrypoint: bash
    args: [
      '-c',
      'pnpm install && pnpm test',
    ]
options:
  logging: CLOUD_LOGGING_ONLY
