steps:
  - name: 'node:latest'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        npm install -g pnpm &&
        pnpm install &&
        pnpm test
options:
  logging: CLOUD_LOGGING_ONLY
