steps:
  - id: 'Node Install'
    name: 'node:latest'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        npm install -g pnpm &&
        pnpm install
  - id: 'Node Test'
    name: 'node:latest'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        pnpm test
  - id: 'Node Lint'
    name: 'node:latest'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        pnpm lint
options:
  logging: CLOUD_LOGGING_ONLY
