steps:
  - id: 'Node Test'
    name: 'node:latest'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        npm install -g pnpm &&
        pnpm install &&
        pnpm test
  - id: 'Node Lint'
    name: 'node:latest'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        npm install -g pnpm &&
        pnpm install &&
        pnpm lint
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/fourth-tiger-437722-i4/cloud-run-source-deploy/url-chopper:tag1', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/fourth-tiger-437722-i4/cloud-run-source-deploy/url-chopper:tag1']
options:
  logging: CLOUD_LOGGING_ONLY
